### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by samhh** [zackify/react-router-async-routing#2]
Consuming as an npm module I get this error:

```
ERROR in ./~/react-router-async-routing/dist/index.js
Module not found: Error: Can't resolve '../src/link' in '[...]/node_modules/react-router-async-routing/dist/'
  @ ./~/react-router-async-routing/dist/index.js 2:0-38

Same for `../src/route` and `../src/preload` as well.

**Comment by zackify** [comment]
Oops! I will make a new release here in a few. Sorry

**Comment by zackify** [comment]
Should be good, lmk if anything else happens. Install 0.1.1

**Comment by samhh** [comment]
```
Uncaught ReferenceError: React is not defined
  at route.js
  at index.js
```

My non-async routes work fine in the same file if I take out the async route.

**Comment by zackify** [comment]
I always have react as a global in my app... sorry I will test this out
with the module from npm in a fresh CRA and get it fixed today

**Comment by zackify** [comment]
@SamHH 0.2.0 pull that in.

**Comment by samhh** [comment]
Fixed! Cheers.

I'm seeing some white flashes between page changes that I didn't used to see with RR3. Am I right in thinking this is down to a limitation in RR4?

**Comment by zackify** [comment]
No, that should not be happening. It’s using almost the exact code from this on constructionjobs.com. Go there and click on a few pages. No flash. Share your code, if you are returning null before an Ajax request or something, that’s on you for the flashing

**Comment by samhh** [comment]
The flash is quick/subtle. You're right, I can't see it on your site.

Hmm. Here's the gist of the code:

Router:
```
import React from 'react'
import { Router, Switch } from 'react-router-dom'
import AsyncSetup from 'react-router-async-routing'

const routes = [{
  path: '/hello',
  dataPath: 'hello',
}, {
  path: '/world',
  dataPath: 'world',
}]

const { Route } = AsyncSetup(routes, path => import(`./views/${path}`))

const CompleteRouter = () => (
  <Router>
    <Switch>
      {routes.map(route => <AsyncRoute key={route.path} exact {...route} />)}
    </Switch>
  </Router>
)

export default CompleteRouter
```

The pages are standard React components that never return null. They are wrapped in `react-redux` containers if that's relevant.

I'll create a small repo and try and reproduce if you can't see anything obviously wrong with the above.

**Comment by zackify** [comment]
Can you show the component code. You need to import Link from AsyncSetup

```
const { Route, Link } = AsyncSetup(routes, path => import(`./views/${path}`))
```
use Link from here when routing around your app

**Comment by samhh** [comment]
Ah, that'll be the issue almost certainly, I'm using RR's Link everywhere.

If I'm deep in a page, where am I getting that particular exported link from? The Router file? The package?

**Comment by zackify** [comment]
you should make a file called router.js or something and export `const { Route, Link, Preload } = AsyncSetup(routes, path => import(`./views/${path}`))
`
The link is just this code. it waits for the bundle then switches the page: https://github.com/zackify/react-router-async-routing/blob/master/src/link.js

**Comment by samhh** [comment]
Finally gotten around to doing that (`import { Link } from '../../router'` for example), but I'm still seeing the flashing. Here's roughly what I have:

router:
```javascript
const userRoutes = [{ path: '/example', dataPath: 'example/index' }] // (and many more)
const adminRoutes = [{ path: '/adminExample', dataPath: 'adminExample/index' }]

const allRoutes = userRoutes.concat(adminRoutes);

export const { Route: AsyncRoute, Link, Preload } = AsyncSetup(allRoutes, path => import(`./${path}`))

// <Route> is RRD's sync Route imported at top. Not expecting these links/routes to be async
const MyRouter = () => (
  <Router>
    <Switch>
      <Route exact path="/login" component={Login} />

      <Route path="/admin">
        <AdminWrapper>
          {adminRoutes.map(route => <Route key={route.path} {...route} />)}
        </AdminWrapper>
      </Route>

      // To clarify, these are the routes/links I am expecting to be async. They are still flashing on change, despite only interacting with and moving around pages in this cluster
      <Route path="/user">
        <UserWrapper>
          {userRoutes.map(route => <AsyncRoute key={route.path} {...route} />)}
        </UserWrapper>
      </Route>
    </Switch>
  </Router>
)
```

**Comment by zackify** [comment]
Have you looked at the example? https://github.com/zackify/react-router-async-routing/blob/master/example/App.js how are you using the link?

**Comment by samhh** [comment]
Yep. So my `example/index.jsx` might be for example:

```javascript
import React from 'react'
import { Link } from '../pages/router'

const Example = () => (
  <div>
    <div>other stuff...</div>
    <Link to="/example2">Click me!</Link>
  </div>
)

export default Example
```

Where `/example2` is another async route. Though of course a lot more stuff that makes the flickering actually noticeable.

**Comment by zackify** [comment]
Sorry about all the problems. I never setup a good test suite for this one like my other projects. I think I was missing preventing the link change in the onClick and made a new release. Hopefully `0.2.1` works. Let me know.

**Comment by samhh** [comment]
That seems to have done the trick, thanks!
