### ISSUE TITLE
Don't import PropTypes from React package

### ISSUE THREAD

**Issue by samhh** [zackify/react-router-async-routing#3]
https://github.com/zackify/react-router-async-routing/blob/master/src/link.js#L35

React 16+ has removed PropTypes from the main library over to a new one called `prop-types`, meaning that this module breaks on load w/ React 16: `Uncaught TypeError: Cannot read property 'object' of undefined`

**Comment by zackify** [comment]
Want to make a pr that just adds the proptypes library? :)
